meshing now under extras_require
jhuapl-boss/intern pull request #85
Opened 2021-08-10 20:00 UTC by ttorir

Tested install on python 3.6.14, 3.7.11, 3.8.11, 3.9.5, 3.9.6 for both general intern and intern['meshing'].

2021-08-11 13:32 UTC, movestill commented
Looks fine, but waiting for the tests to run. Looks like GitHub might be having some problems.

2021-08-13 15:09 UTC, j6k4m8 approved these changes
Nice!!

2021-08-17 20:39 UTC, movestill requested changes

2021-08-17 20:39 UTC, movestill commented on .github/workflows/tests.yml
>          pip install -r requirements.txt
So we don't have to maintain version info both here and in `setup.py`, let's try installing this way:
```
pip install -e .[brotli,cloud-volume,zmesh]
```

2021-08-18 16:57 UTC, movestill approved these changes

2021-08-19 15:40 UTC, merged

2021-08-19 15:53 UTC, j6k4m8 commented
Can you add this to the changelog file when you get a chance, for the next unreleased version?